Repository C3-Zally/frontend, pull requests merged in 2020-08, with the labels that each got.

#23 Feature: Add nav component
  .eslintrc.json
  package-lock.json
  package.json
  src/assets/logo-icon.svg
  src/components/Layout/Layout.scss
  src/components/Layout/index.js
  src/components/NavBar/NavBar.scss
  src/components/NavBar/index.js
  src/components/Wrapper/Wrapper.scss
  src/components/Wrapper/index.js
  src/routes/App.js
Labels: help wanted

#24 Feature: SCSS Mixins added
  src/styles/_colors.scss
  src/styles/_mixins.scss
Labels: feature, help wanted, utility

#34 Fix base-color
  src/styles/_colors.scss
Labels: ui

#25 Feature/cards
  src/assets/images/cough.svg
  src/assets/images/diarrhoea.svg
  src/assets/images/fever.svg
  src/assets/images/runny-nose.svg
  src/assets/images/shortness-breath.svg
  src/assets/images/tiredness.svg
  src/components/SymptomsCard/SymptomsCard.scss
  src/components/SymptomsCard/index.js
  src/components/SymptomsCarousel/SymptomsCarousel.scss
  src/components/SymptomsCarousel/index.js
  src/containers/TakeCare/index.js
Labels: feature

#35 fix typo error
  src/containers/TakeCare/index.js
Labels: bug

#37 Fix/mixins
  package-lock.json
  src/components/SymptomsCard/SymptomsCard.scss
  src/components/SymptomsCard/index.js
  src/components/SymptomsCarousel/SymptomsCarousel.scss
  src/components/SymptomsCarousel/index.js
  src/styles/_mixins.scss
Labels: bug

#36 Feature/search country
  src/components/SearchCountryBar/SearchCountryBar.scss
  src/components/SearchCountryBar/index.js
  src/components/Wrapper/index.js
  src/styles/_colors.scss
  src/ui/CountryItem/CountryItem.scss
  src/ui/CountryItem/index.js
  src/ui/OptionButton/OptionButton.scss
  src/ui/OptionButton/index.js
  src/ui/ThemeChanger/index.js
  src/ui/TopBar/TopBar.scss
  src/ui/TopBar/index.js
Labels: enhancement, feature, layout, ui

#38 Enhancement/Add project font family
  .gitignore
  src/components/NavBar/NavBar.scss
  src/components/Wrapper/Wrapper.scss
  src/index.js
  src/styles/_base.scss
  src/styles/_fonts.scss
  src/styles/_mixins.scss
  src/styles/main.scss
Labels: enhancement

#43 Style: Fix z-index and width of NavBar component
  src/components/NavBar/NavBar.scss
Labels: bug

#40 feature title section ready
  src/components/TitleSection/TitleSection.scss
  src/components/TitleSection/index.js
Labels: feature, layout, ui

#46 Style: add dark background color to main section
  src/styles/_base.scss
  src/styles/_colors.scss
Labels: enhancement, feature

#31 Feature/principal banner
  src/assets/mexico.jpg
  src/components/DataCard/DataCard.scss
  src/components/DataCard/index.js
  src/components/IncrementPercentage/IncrementPercentage.scss
  src/components/IncrementPercentage/index.js
  src/components/MainBanner/MainBanner.scss
  src/components/MainBanner/index.js
  src/containers/Home/index.js
  src/styles/_global.scss
  src/utility/numberConverter/index.js
Labels: feature, layout, utility

#39 Feature/search country funtion
  src/components/SearchCountryBar/SearchCountryBar.scss
  src/components/SearchCountryBar/index.js
  src/ui/CountryItem/CountryItem.scss
  src/ui/CountryItem/index.js
  src/utility/arrays/arrays.test.js
  src/utility/arrays/index.js
  src/utility/countries/countries.test.js
  src/utility/countries/index.js
  src/utility/strings/index.js
  src/utility/strings/strings.test.js
Labels: enhancement, feature, ui, utility

#44 Add useCountryImage hook to handle the banner image fetch
  src/components/DataCard/DataCard.scss
  src/components/IncrementPercentage/IncrementPercentage.scss
  src/components/Loader/Loader.scss
  src/components/Loader/index.js
  src/components/MainBanner/MainBanner.scss
  src/components/MainBanner/index.js
  src/containers/Home/index.js
  src/hooks/useCountryImage.js
  src/styles/_base.scss
  src/styles/_colors.scss
Labels: enhancement

#47 Apply changes
  package-lock.json
  package.json
  src/.eslintrc.json
  src/components/DataCard/DataCard.scss
  src/components/IncrementPercentage/IncrementPercentage.scss
  src/components/Loader/Loader.scss
  src/components/Loader/index.js
  src/components/MainBanner/MainBanner.scss
  src/components/MainBanner/index.js
  src/containers/Home/index.js
  src/hooks/useCountryImage.js
  src/styles/_base.scss
  src/styles/_colors.scss
Labels: bug

#49 Add CD action
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  README.md
  package-lock.json
  package.json
Labels: CI/CD, dependencies

#51 Feature/progress chart
  package-lock.json
  package.json
  src/components/ProgressChart/ProgressChart.scss
  src/components/ProgressChart/index.js
  src/containers/Home/index.js
Labels: feature, layout, ui, utility

#53 fix UI adjustments
  src/components/DataCard/DataCard.scss
  src/components/MainBanner/MainBanner.scss
  src/components/SearchCountryBar/SearchCountryBar.scss
  src/components/TitleSection/TitleSection.scss
  src/ui/TopBar/TopBar.scss
Labels: layout, ui

#55 Fix identity git
  .github/workflows/cd.yml
Labels: CI/CD

#56 Add HashRoute
  src/routes/App.js
Labels: CI/CD, layout

#57 fix dependencies
  package-lock.json
  package.json
Labels: dependencies

#59 Fix theme changer icon
  src/ui/ThemeChanger/index.js
Labels: bug

#58 Feature/map
  package-lock.json
  package.json
  src/components/GlobalMap/GlobalMap.scss
  src/components/GlobalMap/index.js
  src/containers/Country/index.js
  src/containers/Global/index.js
  src/containers/Home/index.js
  src/styles/_colors.scss
Labels: feature, ui

#60 Feature/donut chart cards
  .eslintrc.json
  .prettierrc.json
  package-lock.json
  src/.eslintrc.json
  src/components/DonutChart/DonutChart.js
  src/components/DonutChart/DonutChart.scss
  src/components/DonutChart/index.js
  src/components/Wrapper/Wrapper.scss
  src/containers/Home/Home.scss
  src/containers/Home/index.js
  src/containers/TakeCare/index.js
Labels: feature, help wanted

#63 Combine Componentes
  .eslintrc.json
  .prettierrc.json
  package-lock.json
  package.json
  src/.eslintrc.json
  src/assets/images/avoid-crowds.svg
  src/assets/images/desinfection.svg
  src/assets/images/mask.svg
  src/assets/images/prevention.svg
  src/assets/images/soap.svg
  src/assets/images/stay-at-home.svg
  src/assets/images/wash-hand.svg
  src/components/CareCard/CareCard.scss
  src/components/CareCard/index.js
  src/components/CareCardPrevention/CareCardPrevention.scss
  src/components/CareCardPrevention/index.js
  src/components/CareCards/CareCards.scss
  src/components/CareCards/index.js
  src/components/DataCard/index.js
  src/components/DonutChart/DonutChart.js
  src/components/DonutChart/DonutChart.scss
  src/components/DonutChart/index.js
  src/components/GlobalMap/GlobalMap.scss
  src/components/GlobalMap/index.js
  src/components/IncrementPercentage/index.js
  src/components/SearchCountryBar/SearchCountryBar.scss
  src/components/SymptomsCard/SymptomsCard.scss
  src/components/SymptomsCarousel/SymptomsCarousel.scss
  src/components/SymptomsCarousel/index.js
  src/components/TakeCareContainer/TakeCareContainer.scss
  src/components/TakeCareContainer/index.js
  src/components/Wrapper/Wrapper.scss
  src/components/Wrapper/index.js
  src/containers/Country/index.js
  src/containers/Global/index.js
  src/containers/Home/Home.scss
  src/containers/Home/index.js
  src/containers/TakeCare/index.js
  src/styles/_colors.scss
  src/styles/_global.scss
  src/ui/ThemeChanger/index.js
  src/ui/TopBar/TopBar.scss
  src/utility/numberConverter/index.js
Labels: CI/CD, feature, layout, ui
